---

name: ansible lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: pip3 install ansible ansible-lint

      - name: lint playbook
        run: ansible-lint
